name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Start FastAPI application
        run: |
          uvicorn main:app --reload &
          sleep 10
      
      - name: Fill the table
        run: |
          python app/api_db.py
      
      - name: Run Pytest
        run: |
          pytest
      
      - name: Build and push Docker image
        uses: azure/docker-login@v1
        with:
          login-server: seattlereg.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - run: docker build . -t seattlereg.azurecr.io/seattlebeb-image:latest
      - run: docker push seattlereg.azurecr.io/seattlebeb-image:latest
